In [1]:
import pandas as pd
import numpy as np
import sys
sys.path.append('../utils')
from vectorizer import tf_idf_generator, incidence_matrix_generator
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('annotated_sample.csv')

In [3]:
tf_idf_mat = tf_idf_generator(df,'text')
incidence_mat = incidence_matrix_generator(df,'text')

In [4]:
X = incidence_mat
y = df['value_label']

In [5]:
X

,act,address,and,annual,approximately,area,charter,check,code,commission,...,suite,telephone,the,transition,united,voting,was,wellknown,year,yes
0,0,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
1,1,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
9,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
11,1,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,1
12,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,1,1,0,0,0

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

In [5]:
import pandas as pd
import numpy as np
import os

def merge_csv(folder_path):
    # 获取文件夹中的所有文件
    files = os.listdir(folder_path)
    
    # 初始化一个空的 DataFrame 列表
    df_list = []
    
    # 遍历所有文件
    for file in files:
        # 构建完整的文件路径
        file_path = os.path.join(folder_path, file)
        
        # 检查文件是否是一个 CSV 文件
        if file.endswith('.csv'):
            # 读取 CSV 文件
            df = pd.read_csv(file_path)
            
            # 检查并删除空行
            df = df.dropna(how='all')
            
            # 将清理过的 DataFrame 添加到列表中
            df_list.append(df)
    
    # 检查是否有 CSV 文件被读取
    if not df_list:
        return "No CSV files found in the specified folder."
    
    # 合并所有的 DataFrame
    merged_df = pd.concat(df_list, ignore_index=True)
    
    return merged_df


path = '/Users/weichentao/Documents/USC/2023fall/540/project/select_valuable/cleaned/cleaned_merged_training_data.csv'
df = merge_csv(path)
df

,annotation_id,annotator,created_at,id,lead_time,sentiment,text
0,408.0,1.0,2023-10-26T21:24:22.563707Z,81920.0,2.179,No,ANNUAL REPORT PURSUANT SECTION 13 15d THE
1,1865.0,1.0,2023-10-30T04:26:45.092558Z,81951.0,7.751,No,Disclosures about Market Risk
2,1920.0,1.0,2023-10-30T04:36:59.740406Z,82085.0,2.386,Yes,Although our stated business strategy not enga...
3,960.0,1.0,2023-10-27T00:37:27.775388Z,82097.0,3.216,No,December 31 2016 total debt outstanding was 10...
4,1694.0,1.0,2023-10-27T23:29:27.324892Z,82111.0,1.967,Yes,Directors does not present intend establish se...
...,...,...,...,...,...,...,...
6015,193.0,1.0,2023-10-25T23:53:59.804068Z,141933.0,2.025,No,The weightedaverage grant date fair value opti...
6016,121.0,1.0,2023-10-25T23:43:21.362305Z,142021.0,1.211,No,Net income per weighted average share basic
6017,793.0,1.0,2023-10-30T02:50:00.060265Z,142110.0,1.202,No,Net income per weighted average share basic
6018,1168.0,1.0,2023-10-31T13:01:54.825205Z,142119.0,0.602,No,230 million shares common stock subsequently i...
6019,842.0,1.0,2023-10-31T06:53:32.811159Z,142140.0,14955.471,No,The information contained the section titled S...

In [11]:
path = '/Users/weichentao/Documents/USC/2023fall/540/project/select_valuable/cleaned/cleaned_merged_training_data.csv'
df = pd.read_csv(path)
df

,annotation_id,annotator,created_at,id,lead_time,sentiment,text,cleaned_text
0,408.0,1.0,2023-10-26T21:24:22.563707Z,81920.0,2.179,No,ANNUAL REPORT PURSUANT SECTION 13 15d THE,annual report pursuant section
1,1865.0,1.0,2023-10-30T04:26:45.092558Z,81951.0,7.751,No,Disclosures about Market Risk,disclosure market risk
2,1920.0,1.0,2023-10-30T04:36:59.740406Z,82085.0,2.386,Yes,Although our stated business strategy not enga...,although stated business strategy engage acqui...
3,960.0,1.0,2023-10-27T00:37:27.775388Z,82097.0,3.216,No,December 31 2016 total debt outstanding was 10...,december total debt outstanding ratio total de...
4,1694.0,1.0,2023-10-27T23:29:27.324892Z,82111.0,1.967,Yes,Directors does not present intend establish se...,director present intend establish series prefe...
...,...,...,...,...,...,...,...,...
6015,193.0,1.0,2023-10-25T23:53:59.804068Z,141933.0,2.025,No,The weightedaverage grant date fair value opti...,weightedaverage grant date fair value option g...
6016,121.0,1.0,2023-10-25T23:43:21.362305Z,142021.0,1.211,No,Net income per weighted average share basic,net income per weight average share basic
6017,793.0,1.0,2023-10-30T02:50:00.060265Z,142110.0,1.202,No,Net income per weighted average share basic,net income per weight average share basic
6018,1168.0,1.0,2023-10-31T13:01:54.825205Z,142119.0,0.602,No,230 million shares common stock subsequently i...,million share common stock subsequently issue ...
6019,842.0,1.0,2023-10-31T06:53:32.811159Z,142140.0,14955.471,No,The information contained the section titled S...,information contain section title security own...

In [12]:
print(df['cleaned_text'].isnull().sum())

6

In [10]:
df['cleaned_text'] = df['cleaned_text'].fillna('')
print(df['cleaned_text'].isnull().sum())

0

In [13]:
path = '/Users/weichentao/Documents/USC/2023fall/540/project/select_valuable/cleaned/tf_idf.csv'
df = pd.read_csv(path)
df

,aa,aaa,aada,aaia,aam,aamc,aame,aareal,ab,abandon,...,zertane,zhonghong,zhongtai,zilretta,zip,zixit,zone,zonge,zvex,sentiment.1
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.092179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Yes
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No
6016,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No
6017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No
6018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No
6019,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No

In [16]:
df.iloc[:,-1].unique()

array(['No', 'Yes', nan], dtype=object)

In [17]:
value_counts = df.iloc[:, -1].value_counts()
value_counts

No     4146
Yes    1863
Name: sentiment.1, dtype: int64

In [18]:
missing_values = df.iloc[:, -1].isnull().sum()
print(missing_values)

11

In [19]:
missing_values = df.isnull().sum()
columns_with_missing_values = missing_values[missing_values > 0]
print(columns_with_missing_values)

sentiment.1    11
dtype: int64

In [20]:
path2 = '/Users/weichentao/Documents/USC/2023fall/540/project/select_valuable/cleaned/cleaned_merged_training_data.csv'
df = pd.read_csv(path2)
missing_values = df.isnull().sum()
columns_with_missing_values = missing_values[missing_values > 0]
print(columns_with_missing_values)

sentiment       11
cleaned_text     6
dtype: int64

In [21]:
paths = ['/Users/weichentao/Documents/USC/2023fall/540/project/select_valuable/first_labeled/labeled_2016.csv',
        '/Users/weichentao/Documents/USC/2023fall/540/project/select_valuable/first_labeled/labeled_2017.csv',
        '/Users/weichentao/Documents/USC/2023fall/540/project/select_valuable/first_labeled/labeled_2018.csv']
for path in paths:
    df = pd.read_csv(path)
    print("Current path:",path)
    missing_values = df.isnull().sum()
    columns_with_missing_values = missing_values[missing_values > 0]
    print(columns_with_missing_values)

Current path: /Users/weichentao/Documents/USC/2023fall/540/project/select_valuable/first_labeled/labeled_2016.csv
sentiment    2
dtype: int64
Current path: /Users/weichentao/Documents/USC/2023fall/540/project/select_valuable/first_labeled/labeled_2017.csv
annotation_id    2001
annotator        2001
created_at       2001
id               2001
lead_time        2001
sentiment        2006
text             2001
dtype: int64
Current path: /Users/weichentao/Documents/USC/2023fall/540/project/select_valuable/first_labeled/labeled_2018.csv
sentiment    4
dtype: int64